### ISSUE TITLE
Exception which make PhpStorm 2020.3 EAP stuck on "Analysing..." file

### ISSUE THREAD

**Issue by TrueXakeP** [funivan/PhpClean#127]
First sorry for my english.

While PhpClean is enabled a PhpStorm stuck on "Analysing..." and rich coloring of a file not working. When I disable the PhpClean a coloring start working.

Many identical sections contains in the log:
```
2020-11-05 02:14:01,621 [7568535]  ERROR - aemon.impl.PassExecutorService - PhpStorm 2020.3 EAP  Build #PS-203.5419.32 
2020-11-05 02:14:01,621 [7568535]  ERROR - aemon.impl.PassExecutorService - JDK: 11.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-11-05 02:14:01,621 [7568535]  ERROR - aemon.impl.PassExecutorService - OS: Windows 10 
2020-11-05 02:14:01,621 [7568535]  ERROR - aemon.impl.PassExecutorService - Plugin to blame: PhpClean version: 2020.11.04-alpha 
2020-11-05 02:14:01,622 [7568536]  ERROR - aemon.impl.PassExecutorService - Last Action: ComposerDiagnoseAction 
2020-11-05 02:14:02,198 [7569112]  ERROR - aemon.impl.PassExecutorService - com.funivan.idea.phpClean.inspections.parentPropertyDeprecated.ParentPropertyDeprecatedInspection PluginClassLoader[PluginDescriptor(name=PhpClean, id=com.funivan.idea.phpClean, path=C:\Users\root\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\203.5419.32.plugins\PhpClean, version=2020.11.04-alpha)] com.intellij.ide.plugins.cl.PluginClassLoader@277d2063 [Plugin: com.funivan.idea.phpClean] 
com.intellij.diagnostic.PluginException: com.funivan.idea.phpClean.inspections.parentPropertyDeprecated.ParentPropertyDeprecatedInspection PluginClassLoader[PluginDescriptor(name=PhpClean, id=com.funivan.idea.phpClean, path=C:\Users\root\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\203.5419.32.plugins\PhpClean, version=2020.11.04-alpha)] com.intellij.ide.plugins.cl.PluginClassLoader@277d2063 [Plugin: com.funivan.idea.phpClean]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:750)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:43)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.createInstance(CustomLoadingExtensionPointBean.java:29)
	at com.intellij.codeInspection.InspectionEP.instantiateTool(InspectionEP.java:206)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:76)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.getInspectionTools(LocalInspectionsPass.java:741)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:115)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: com.funivan.idea.phpClean.inspections.parentPropertyDeprecated.ParentPropertyDeprecatedInspection PluginClassLoader[PluginDescriptor(name=PhpClean, id=com.funivan.idea.phpClean, path=C:\Users\root\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\203.5419.32.plugins\PhpClean, version=2020.11.04-alpha)] com.intellij.ide.plugins.cl.PluginClassLoader@277d2063
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:117)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:747)
	... 25 more
```

**Comment by funivan** [comment]
Thanks for the report.
Working on fix right now.

**Comment by funivan** [comment]
Hello @TrueXakeP 
Can you try to install the latest Alpha version and check it? 

Download JAR file from this page https://github.com/funivan/PhpClean/releases/tag/2020.11.05-alpha and install it from disk.

Also, you can reinstall the plugin in the IDE. I have dropped the last buggy version.

**Comment by TrueXakeP** [comment]
It seems that indexing and coloring start to work. Thank you.
