### ISSUE TITLE
Exception on PhpStorm 2020.2.3 with PhpClean 2020-12-02

### ISSUE THREAD

**Issue by Etienne-Schmitt** [funivan/PhpClean#140]
PhpStorm 2020.2.3
Build #PS-202.7660.42, built on October 16, 2020
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7

```
java.lang.ClassCastException: class com.jetbrains.php.lang.documentation.phpdoc.psi.impl.PhpDocVarImpl cannot be cast to class com.jetbrains.php.lang.documentation.phpdoc.psi.PhpDocType (com.jetbrains.php.lang.documentation.phpdoc.psi.impl.PhpDocVarImpl and com.jetbrains.php.lang.documentation.phpdoc.psi.PhpDocType are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @4cdd55e7)
	at com.funivan.idea.phpClean.inspections.redundantDocCommentTag.RedundantDocCommentTagInspection$buildVisitor$1.checkComment(RedundantDocCommentTagInspection.kt:56)
	at com.funivan.idea.phpClean.inspections.redundantDocCommentTag.RedundantDocCommentTagInspection$buildVisitor$1.visitPhpFunction(RedundantDocCommentTagInspection.kt:37)
	at com.funivan.idea.phpClean.inspections.redundantDocCommentTag.RedundantDocCommentTagInspection$buildVisitor$1.visitPhpMethod(RedundantDocCommentTagInspection.kt:25)
	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:93)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$6(LocalInspectionsPass.java:319)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:168)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:110)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:319)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)```

**Comment by funivan** [comment]
Thanks for the issue. Can you provide a part of the code and steps to reproduce?

**Comment by Etienne-Schmitt** [comment]
It happened while indexing a 5.1 symfony project.

I was thinking it was a vendor 5.1 problem because I didn't get an error on a full 5.2 new test project, but get one on a 5.1, but after many tries without error I retried a new full 5.1 and then everything worked...
I don't understand why...

Sorry not to be of much help...

But I did notice than I didn't post correclty the error... I writed ```blablabla instead of ```\nblablabla so the error was not completly showed.... I edited it.... I hope it could be useful

**Comment by funivan** [comment]
Can you try the following version of the plugin https://github.com/funivan/PhpClean/releases/tag/2020.12.15-nightly
Click Download JAR and install plugin from disk.

**Comment by funivan** [comment]
Fixed in https://plugins.jetbrains.com/plugin/11272-phpclean/versions/stable/106135 

Update your plugin in the IDE. Thanks for the report 👍
